# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "notebooks"
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-toml
  - id: check-added-large-files
# - repo: https://github.com/astral-sh/ruff-pre-commit
  # rev: v0.2.1
  # hooks:
  # - id: ruff
  # - id: ruff-format
- repo: local
  hooks:
    - id: ruff check
      name: ruff check
      entry: ruff check .
      language: system
      pass_filenames: false
      always_run: true
    - id: ruff format
      name: ruff format
      entry: ruff format .
      language: system
      pass_filenames: false
      always_run: true
    - id: mypy
      name: mypy
      entry: mypy src
      language: system
      pass_filenames: false
      always_run: true
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
