[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11.6"
dependencies = []

[project.scripts]
app = "app:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
